version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/src/ai-training"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
